### DISCUSSION TITLE
Charge Amps Aura missing functionality

### DISCUSSION THREAD

**Discussion by Miggle007** [hass-chargeamps/hass-chargeamps#68] [Q&A] [answered]
I am gladly using this integration and I am able to do the following:

- Read the current power usage per connector (the Aura has two connectors)
- View the actual status per connector (available, charging, ..)
- Switch the connector on or off
- Dim the light
- Read the total consumed energy

However, I am mainly missing the thing that I want to automate on: Set the current per connector. When taking a look at the REST API documentation this is available. When digging in to this custom component it seems to be built in to this integration.

Does anyone recognize this? 
Does this also has to do with the CAPI > OCPP?

**Comment by ReconOperator** [comment]
Maybe I'm missunderstanding you, but have you checked the documentation here?
https://github.com/kirei/hass-chargeamps?tab=readme-ov-file#services

set_max_current -- set max current for connector

I have a Halo with OCPP and I can set the max current with this Action in HA

![Screenshot_20241116_232447_Home Assistant](https://github.com/user-attachments/assets/bc311cf5-175b-4678-b4fc-efedbdd19e30)

You can test it under developer tools

![Screenshot_20241116_232703_Home Assistant](https://github.com/user-attachments/assets/e647dd57-3101-47eb-99d5-97baafb1a9ba)

**Comment by tretabyte** [comment]
> ![Screenshot_20241116_232447_Home Assistant](https://private-user-images.githubusercontent.com/89938458/386881767-bc311cf5-175b-4678-b4fc-efedbdd19e30.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDQ3ODEsIm5iZiI6MTczMjEwNDQ4MSwicGF0aCI6Ii84OTkzODQ1OC8zODY4ODE3NjctYmMzMTFjZjUtMTc1Yi00Njc4LWI0ZmMtZWZlZGJkZDE5ZTMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEyMDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNDYyZDVhYjZmMmE2OTY5YTM3ZWM5MjdjNzM3NGRiYTgwNWUzNDM2NjAyOWIwNTljNmQxMDAzZmExNmZiZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E5auQJIi57N53QXQ69uB878wau9-gLTotgevJX2NDDo)

Hi,
did you build yourself the "Set Max Current"?, I've been trying to do it, but I don't have enough skills for it (I even made a post request here to see if we can get that by default with no luck).
Another thing that would be useful would be to have a remote start and remote stop buttons, that way you can always turn it on but not start the charging until you really want it to.

**Comment by ReconOperator** [comment, marked as answer]
> > ![Screenshot_20241116_232447_Home Assistant](https://private-user-images.githubusercontent.com/89938458/386881767-bc311cf5-175b-4678-b4fc-efedbdd19e30.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDQ3ODEsIm5iZiI6MTczMjEwNDQ4MSwicGF0aCI6Ii84OTkzODQ1OC8zODY4ODE3NjctYmMzMTFjZjUtMTc1Yi00Njc4LWI0ZmMtZWZlZGJkZDE5ZTMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDEyMDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNDYyZDVhYjZmMmE2OTY5YTM3ZWM5MjdjNzM3NGRiYTgwNWUzNDM2NjAyOWIwNTljNmQxMDAzZmExNmZiZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E5auQJIi57N53QXQ69uB878wau9-gLTotgevJX2NDDo)
> 
> Hi, did you build yourself the "Set Max Current"?, I've been trying to do it, but I don't have enough skills for it (I even made a post request here to see if we can get that by default with no luck). Another thing that would be useful would be to have a remote start and remote stop buttons, that way you can always turn it on but not start the charging until you really want it to.

Yes i have done an automation for the "Set Max Current" that uses input from a input select helper.

alias: Halo Set Max Current
description: Set Max current on Charge Amps Halo
mode: single
triggers:
  - entity_id:
      - input_select.set_current
    trigger: state
conditions: []
actions:
  - data:
      chargepoint: "redacted"
      connector: 1
      max_current: |-
        {% if is_state("input_select.set_current", "6") %}
          6
        {% elif is_state("input_select.set_current", "8") %}
          8
        {% elif is_state("input_select.set_current", "10") %}
          10
        {% elif is_state("input_select.set_current", "12") %}
          12
        {% elif is_state("input_select.set_current", "14") %}
          14
        {% elif is_state("input_select.set_current", "16") %}
          16
        {% else %}
          Unknown
        {% endif %}
    action: chargeamps.set_max_current
    
![Capture](https://github.com/user-attachments/assets/d88f4624-3758-4c83-8dcc-7140a4502fc8)

**Comment by tretabyte** [comment]
mind sharing the entire yaml for that automatition?

this is what I have and its supposed to work but somehow it doesn't do the change
```
alias: chargeamp set_current
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_select.set_current
conditions: []
actions:
  - action: chargeamps.set_max_current
    data:
      chargepoint: XXXXXXXXXX
      connector: 1
      max_current: |-
        {% if is_state("input_select.set_current", "6") %}
        6
        {% elif is_state("input_select.set_current", "8") %}
        8
        {% elif is_state("input_select.set_current", "10") %}
        10
        {% elif is_state("input_select.set_current", "12") %}
        12
        {% elif is_state("input_select.set_current", "14") %}
        14
        {% elif is_state("input_select.set_current", "16") %}
        16
        {% elif is_state("input_select.set_current", "18") %}
        18
        {% elif is_state("input_select.set_current", "20") %}
        20
        {% elif is_state("input_select.set_current", "22") %}
        22
        {% elif is_state("input_select.set_current", "24") %}
        24
        {% elif is_state("input_select.set_current", "26") %}
        26
        {% else %}
        Unknown
        {% endif %}
mode: single
```

**Comment by ReconOperator** [comment]
I shared the complete .yaml of the automation.

Did you create the input_select.set_current helper?

**Comment by tretabyte** [comment]
> I shared the complete .yaml of the automation.
> 
> Did you create the input_select.set_current helper?

yep I did and the selector works
wait.. I think it's working, somehow it takes like 1min or so to update but it works
thank you very much for the help :)

**Comment by Miggle007** [comment]
Hi @ReconOperator, Many many thanks for this! I've been looking everywhere except in developer tools. I've tested it just now and indeed this works perfectly. I'll create some sort of input selector the way you did in order to use it in manually changing and and mostly in automizing (peak shaving) this. Great and thanks again. My issue has been resolved.

**Comment by Miggle007** [comment]
My issue has been resolved by using the developer tools

**Comment by Miggle007** [comment]
@tretabyte I have created a slightly different automation. Perhaps it's useful for you as well. I have created a slider helper from 6A (minimum supported by ChargeAmps) to 16A (maximum in my case) called _input_number.maximum_current_connector_1_left_. Furthermore I have two helpers and two automations, because I need to be able to set the max_current for each connect independantly.

This results in a slightly shortened automation:

```
alias: chargeamps set current L
description: Set Current for ChargeAmps Aura Connector 1
triggers:
  - trigger: state
    entity_id:
      - input_number.maximum_current_connector_1_left
conditions: []
actions:
  - action: chargeamps.set_max_current
    data:
      chargepoint: 1234567890A
      connector: 1
      max_current: |
        {{ states("input_number.maximum_current_connector_1_left") }}
mode: single
```

**Comment by tretabyte** [comment]
> @tretabyte I have created a slightly different automation. Perhaps it's useful for you as well. I have created a slider helper from 6A (minimum supported by ChargeAmps) to 16A (maximum in my case) called _input_number.maximum_current_connector_1_left_. Furthermore I have two helpers and two automations, because I need to be able to set the max_current for each connect independantly.
> 
> This results in a slightly shortened automation:
> 
> > alias: chargeamps set current L
> > description: Set Current for ChargeAmps Aura Connector 1
> > triggers:
> > 
> > * trigger: state
> >   entity_id:
> >   
> >   * input_number.maximum_current_connector_1_left
> >     conditions: []
> >     actions:
> > * action: chargeamps.set_max_current
> >   data:
> >   chargepoint: 1234567890A
> >   connector: 1
> >   max_current: |
> >   {{ states("input_number.maximum_current_connector_1_left") }}
> >   mode: single

Basically you created another automation that will change the input_number depending on which input_silder you picked and then it changes the max_current sent to the charger, is that right?

**Comment by Miggle007** [comment]
> > @tretabyte I have created a slightly different automation. Perhaps it's useful for you as well. I have created a slider helper from 6A (minimum supported by ChargeAmps) to 16A (maximum in my case) called _input_number.maximum_current_connector_1_left_. Furthermore I have two helpers and two automations, because I need to be able to set the max_current for each connect independantly.
> > This results in a slightly shortened automation:
> > > alias: chargeamps set current L
> > > description: Set Current for ChargeAmps Aura Connector 1
> > > triggers:
> > > 
> > > * trigger: state
> > >   entity_id:
> > >   
> > >   * input_number.maximum_current_connector_1_left
> > >     conditions: []
> > >     actions:
> > > * action: chargeamps.set_max_current
> > >   data:
> > >   chargepoint: 1234567890A
> > >   connector: 1
> > >   max_current: |
> > >   {{ states("input_number.maximum_current_connector_1_left") }}
> > >   mode: single
> 
> Basically you created another automation that will change the input_number depending on which input_silder you picked and then it changes the max_current sent to the charger, is that right?

Yes, that's exactly what it does!

**Comment by Miggle007** [comment]
And the last update is my remote start and stop. I've created a helper (boolean on/off) called input_boolean.remote_start_stop_connector_1_left. Again I have two helpers, because of the two connectors on the Aura. I don't think this is the best way or the best way of doing it. Hoewever it does the job for me:

```
alias: Remote Start and Stop
description: Remote Start and Stop
triggers:
  - trigger: state
    entity_id:
      - input_boolean.remote_start_stop_connector_1_left
conditions: []
actions:
  - if:
      - condition: template
        value_template: >-
          {{ is_state('input_boolean.remote_start_stop_connector_1_left','on')
          }}
    then:
      - action: chargeamps.remote_start
        data:
          chargepoint: 1234567890A
          connector: 1
          rfid_length: 4
          rfid_format: Dec
          rfid: 111111111
        target:
          entity_id: chargeamps.remote_start
    else:
      - action: chargeamps.remote_stop
        data:
          chargepoint: 1234567890A
          connector: 1
        target:
          entity_id: chargeamps.remote_stop
mode: single
```
You'll need to wait about 1 minute after a remote start or stop to send a new (inversed) remote start or stop.
